
project_id = "pvtrmpaxhbvhvdiojqkd"

[functions.create-job]
verify_jwt = true

[functions.refine-image]
verify_jwt = true

[functions.generate-model]
verify_jwt = true

[functions.job-status]
verify_jwt = false

[functions.feedback]
verify_jwt = false

[functions.n8n-callback]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

