
project_id = "pvtrmpaxhbvhvdiojqkd"

[functions.create-job]
verify_jwt = false

[functions.refine-image]
verify_jwt = false

[functions.generate-model]
verify_jwt = false

[functions.job-status]
verify_jwt = false
