
project_id = "pvtrmpaxhbvhvdiojqkd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[auth]
enabled = true
port = 9999

[realtime]
enabled = true

[storage]
enabled = true

[analytics]
enabled = false

[functions]
[functions.use-refinement-credit]
verify_jwt = true

[functions.add-test-credits]
verify_jwt = true

[functions.check-model-status]
verify_jwt = false

[functions.generate-model]
verify_jwt = false
